### PR TITLE
Merge remote-tracking branch 'kenold/master'

### PR DESCRIPTION
**Pull request by jeangustavee**
New changes on the cover pictures (html and css)
media query added…

### CODE REVIEW

**Comment by kenold** [comment]
I didn't see the new media queries. Please save the changes and do a new pull request. Thanks.

**Comment by jeangustavee** [comment]
I did. can't you see the other changes? like the pictures and stuff

**Comment by kenold** [comment]
I  see the pictures but no media queries in css

Kenold Beauplan




On Mon, Jun 20, 2016 at 10:50 AM -0400, "Jean Gustave" <notifications@github.com> wrote:












I did. can't you see the other changes? like the pictures and stuff

**Comment by jeangustavee** [comment]
it’s in the main css

**Pull request merged**
